<?php
/**
 * @file
 * Code for the Marketing Landing Page feature.
 */

include_once 'marketing_landing_page.features.inc';

// =====================
// = Add Node Template =
// =====================

/**
 * Implements hook_theme().
 */
function marketing_landing_page_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['node__landing_page'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--landing_page',
    'path' => drupal_get_path('module', 'marketing_landing_page') . '/template',
  );
  return $theme;
}